
let DATA={tests:[],stats:{}};
let state={category:'Tümü',search:'',test:null,index:0,answers:{},finished:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function categoryIcon(cat){return {'Anadolu Destanı':'🏺','Antik Kentler ve Müzeler':'🏛️','Coğrafya ve Turizm':'🗺️','Türkiye Coğrafyası':'🌍','Türk Sanatı ve Kültürel Miras':'🎨'}[cat]||'📚'}
function filtered(){return DATA.tests.filter(t=>(state.category==='Tümü'||t.category===state.category)&&(`${t.title} ${t.subtitle} ${t.category} ${t.source}`.toLocaleLowerCase('tr').includes(state.search.toLocaleLowerCase('tr'))))}
function buildMenu(){const cats=['Tümü',...new Set(DATA.tests.map(t=>t.category))];$('#categoryMenu').innerHTML=cats.map(c=>`<button class="nav-btn ${c===state.category?'active':''}" data-cat="${esc(c)}"><span>${c==='Tümü'?'🏠':categoryIcon(c)}</span><span>${esc(c==='Tümü'?'Ana Sayfa':c)}</span><span class="count">${c==='Tümü'?DATA.tests.length:DATA.tests.filter(t=>t.category===c).length}</span></button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.test=null;state.finished=false;buildMenu();renderHome();closeMobile()})}
function renderStats(){const s=DATA.stats;$('#stats').innerHTML=`<div class="stat"><strong>${s.questions.toLocaleString('tr-TR')}</strong><span>toplam soru</span></div><div class="stat"><strong>${s.tests}</strong><span>test kartı</span></div><div class="stat"><strong>${s.categories}</strong><span>ana kategori</span></div><div class="stat"><strong>Anında</strong><span>doğru-yanlış kontrolü</span></div>`;$('#sideStats').textContent=`${s.questions.toLocaleString('tr-TR')} soru • ${s.tests} test kartı`;$('#heroCount').textContent=s.questions.toLocaleString('tr-TR')}
function renderHome(){state.test=null;state.finished=false;$('#pageTitle').textContent=state.category==='Tümü'?'Ana Sayfa':state.category;$('#home').classList.remove('hidden');$('#testView').classList.add('hidden');$('#resultView').classList.add('hidden');const list=filtered();$('#listTitle').textContent=state.category==='Tümü'?'Tüm Testler':state.category;$('#listDesc').textContent=state.search?`“${state.search}” araması için ${list.length} sonuç`:`${list.length} test kartı`;$('#cards').innerHTML=list.length?list.map(t=>`<article class="card"><div class="card-top"><span class="pill">${categoryIcon(t.category)} ${esc(t.category)}</span><span class="pill">${t.questions.length} soru</span></div><h4>${esc(t.title)}</h4><p>${esc(t.subtitle)}</p><div class="card-footer"><span>${esc(t.source)}</span><button class="primary" data-start="${t.id}">Teste Başla</button></div></article>`).join(''):`<div class="empty">Aramana uygun test bulunamadı.</div>`;$$('[data-start]').forEach(b=>b.onclick=()=>startTest(b.dataset.start));window.scrollTo({top:0,behavior:'smooth'})}
function startTest(id){state.test=DATA.tests.find(t=>t.id===id);state.index=0;state.answers={};state.finished=false;$('#home').classList.add('hidden');$('#resultView').classList.add('hidden');$('#testView').classList.remove('hidden');$('#pageTitle').textContent=state.test.title;renderQuestion();closeMobile();window.scrollTo({top:0,behavior:'smooth'})}
function renderQuestion(){const t=state.test,q=t.questions[state.index],ans=state.answers[q.id];$('#testTitle').textContent=t.title;$('#testSubtitle').textContent=`${t.subtitle} • ${t.questions.length} soru`;$('#qCounter').textContent=`Soru ${state.index+1} / ${t.questions.length}`;$('#qProgressSource').textContent=`Kaynak soru no: ${q.sourceNumber}`;$('#qSource').textContent=`Soru ${state.index+1}`;$('#progressBar').style.width=`${((state.index+1)/t.questions.length)*100}%`;$('#questionText').textContent=q.question;$('#options').innerHTML=q.options.map(o=>{let cls='option';if(ans){if(o.letter===q.answer)cls+=' correct';else if(o.letter===ans.choice)cls+=' wrong'}return `<button class="${cls}" data-choice="${o.letter}" ${ans?'disabled':''}><span class="letter">${o.letter}</span><span>${esc(o.text)}</span></button>`}).join('');const fb=$('#feedback');fb.className='feedback';fb.innerHTML='';if(ans){const ok=ans.choice===q.answer;fb.classList.add('show',ok?'correct':'wrong');fb.innerHTML=`<strong>${ok?'✓ Doğru cevap':'✕ Yanlış cevap'}</strong>${esc(q.explanation)}`;$('#nextBtn').disabled=false}else{$('#nextBtn').disabled=true}$$('[data-choice]').forEach(b=>b.onclick=()=>answer(b.dataset.choice));$('#nextBtn').textContent=state.index===t.questions.length-1?'Testi Bitir':'Sonraki Soru';renderJump()}
function answer(choice){const q=state.test.questions[state.index];if(state.answers[q.id])return;state.answers[q.id]={choice,correct:choice===q.answer};renderQuestion()}
function renderJump(){const t=state.test;$('#jump').innerHTML=t.questions.map((q,i)=>`<button class="dot ${i===state.index?'current':''} ${state.answers[q.id]?'answered':''}" data-jump="${i}">${i+1}</button>`).join('');$$('[data-jump]').forEach(b=>b.onclick=()=>{state.index=Number(b.dataset.jump);renderQuestion();window.scrollTo({top:0,behavior:'smooth'})})}
function next(){const t=state.test;if(!state.answers[t.questions[state.index].id])return;if(state.index<t.questions.length-1){state.index++;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}else finish()}
function finish(){const t=state.test;const answered=Object.keys(state.answers).length,correct=Object.values(state.answers).filter(a=>a.correct).length,wrong=answered-correct,blank=t.questions.length-answered,score=Math.round(correct/t.questions.length*100);state.finished=true;$('#testView').classList.add('hidden');$('#resultView').classList.remove('hidden');$('#pageTitle').textContent='Sonuç';$('#scoreRing').style.setProperty('--score',score);$('#scoreVal').textContent=`%${score}`;$('#resultTitle').textContent=score>=80?'Harika sonuç!':score>=60?'Gayet iyi!':'Bir tekrar daha faydalı olur';$('#resultText').textContent=`${t.title} tamamlandı.`;$('#resultStats').innerHTML=`<div class="result-stat"><strong style="color:var(--green)">${correct}</strong><span>Doğru</span></div><div class="result-stat"><strong style="color:var(--red)">${wrong}</strong><span>Yanlış</span></div><div class="result-stat"><strong>${blank}</strong><span>Boş</span></div>`;$('#review').innerHTML=t.questions.map((q,i)=>{const a=state.answers[q.id];const ok=a?.correct;return `<div class="review-item"><strong class="${ok?'ok':'bad'}">${i+1}. ${ok?'Doğru':'Yanlış / Boş'}</strong><p>${esc(q.question)}</p><small>Doğru cevap: ${q.answer}) ${esc(q.options.find(o=>o.letter===q.answer)?.text||'')}</small></div>`}).join('');$('#resultView').dataset.summary=`${t.title}\nDoğru: ${correct}\nYanlış: ${wrong}\nBoş: ${blank}\nBaşarı: %${score}`;window.scrollTo({top:0,behavior:'smooth'})}
function copyResult(){navigator.clipboard.writeText($('#resultView').dataset.summary||'').then(()=>toast('Sonuç kopyalandı')).catch(()=>toast('Kopyalama başarısız'))}
function closeMobile(){$('#sidebar').classList.remove('open')}
async function init(){DATA=await fetch('test-verileri.json').then(r=>r.json());buildMenu();renderStats();renderHome();$('#searchInput').oninput=e=>{state.search=e.target.value;renderHome()};$('#nextBtn').onclick=next;$('#finishBtn').onclick=finish;$('#backBtn').onclick=renderHome;$('#resultBack').onclick=renderHome;$('#copyBtn').onclick=copyResult;$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open')}
init().catch(err=>{document.body.innerHTML=`<div style="padding:30px;font-family:sans-serif"><h2>Veriler yüklenemedi</h2><p>${esc(err.message)}</p><p>Bu klasörü doğrudan dosya olarak açtıysan küçük bir yerel sunucuyla çalıştır: <code>python -m http.server</code></p></div>`})
